name: Deploy Storybook

on:
  push:
    branches: 
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Clean npm cache
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf ~/.npm
      
      - name: Install root dependencies
        run: npm install
      
      - name: Install package dependencies
        working-directory: ./packages/design-docs
        run: |
          npm install
          npm list
      
      - name: Verify Storybook Installation
        working-directory: ./packages/design-docs
        run: |
          npx @storybook/doctor
          npm list @storybook/react
      
      - name: Build Storybook
        working-directory: ./packages/design-docs
        run: |
          npm install -g @storybook/cli
          npx storybook build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/design-docs/storybook-static
          publish_branch: gh-pages