name: Deploy Storybook

on:
  push:
    branches: 
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install package dependencies
        working-directory: ./packages/design-docs
        run: npm ci
      
      - name: Debug - List Installed Packages
        working-directory: ./packages/design-docs
        run: |
          echo "Installed packages:"
          npm list | grep storybook
          npm list | grep vite
      
      - name: Build Storybook
        working-directory: ./packages/design-docs
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Running Storybook build..."
          npx storybook build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/design-docs/storybook-static
          publish_branch: gh-pages