on:
    push:
      branches:
        - "main" # change to the branch you wish to deploy from
  
permissions:
    contents: read
    pages: write
    id-token: write
  
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      # Manual Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          build_command: npm run build-design-docs
          path: packages/design-docs/storybook-static # default: dist/storybook
          checkout: false # default: true