name: Deploy Storybook

on:
  push:
    branches: [main]

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install package-specific dependencies
        working-directory: ./packages/design-docs  # Adjust this path to your specific Storybook package
        run: npm ci

      - name: Build Storybook
        working-directory: ./packages/design-docs  # Same path as above
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/design-docs/storybook-static  # Path to Storybook build output
          publish_branch: gh-pages