name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main' # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Cache Node.js dependencies
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node20-main-${{ hashFiles('package-lock.json') }}-${{ github.run_id }}
          restore-keys: |
            deps-node20-main-

      # Install dependencies and remove package-lock.json
      - name: Install dependencies and remove package-lock.json
        run: |
          cd ./packages/design-docs
          rm -f package-lock.json
          npm ci

      # Install dependencies for react storybook
      - name: Install dependencies for react storybook
        run: |
          cd ./packages/react
          rm -f package-lock.json
          npm ci

      # Install dependencies for angular storybook
      - name: Install dependencies for angular storybook
        run: |
          cd ./packages/angular
          rm -f package-lock.json
          npm ci

      # Build Design Docs Storybook
      - name: Build Design Docs Storybook
        run: |
          npm run build-design-docs

      # Build Base Storybook
      - name: Build Base Storybook
        run: |
          npm run build-base-storybook

      # Deploy Storybook to GitHub Pages
      - name: Deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: ./packages/design-docs/storybook-static # Path to the built Storybook
          checkout: false